### ISSUE TITLE
Multiple bottles scanning with a zero proof value

### ISSUE THREAD

**Issue by dwminnich** [OnlyDrams/onlydrams#8]
Scanned a Makers Mark private selection, and it entered the proof as 0.  Also happened for: 
        * Jack Daniel’s SBBP Tennessee
        * WhistlePig, 10 year cask strength, single barrel rye

**Comment by tee** [comment]
For single barrels the proof is listed as 0 since, due to the nature of single barrels, these proofs are not constant and have varying proof. For the future after todays update, we will display "Varies" instead of a zero proof point.
